-- 20260627121000_seed_catalog_77.sql
-- Catálogo real: 77 productos oficiales con unidad + categoría.
-- Los oficiales NO pasan por la lista de bloqueo (el trigger solo aplica a custom),
-- así que Antibióticos / Pastillas para la tensión / Pastillas para el dolor cargan bien.
begin;
insert into public.products (name, kind, unit, category) values
  ('Pastillas potabilizadoras', 'official', 'caja', 'Agua e higiene'),
  ('Filtros de agua', 'official', 'unidad', 'Agua e higiene'),
  ('Jabón', 'official', 'unidad', 'Agua e higiene'),
  ('Toallitas húmedas', 'official', 'paquete', 'Agua e higiene'),
  ('Papel higiénico', 'official', 'paquete', 'Agua e higiene'),
  ('Pañales de bebé', 'official', 'paquete', 'Agua e higiene'),
  ('Pañales de adulto', 'official', 'paquete', 'Agua e higiene'),
  ('Toallas sanitarias', 'official', 'paquete', 'Agua e higiene'),
  ('Cepillos dentales', 'official', 'unidad', 'Agua e higiene'),
  ('Pasta dental', 'official', 'unidad', 'Agua e higiene'),
  ('Kits de higiene familiar', 'official', 'caja', 'Agua e higiene'),
  ('Shampoo', 'official', 'unidad', 'Agua e higiene'),
  ('Desodorantes', 'official', 'unidad', 'Agua e higiene'),
  ('Arroz', 'official', 'kg', 'Alimentos no perecederos'),
  ('Pasta', 'official', 'kg', 'Alimentos no perecederos'),
  ('Lentejas', 'official', 'kg', 'Alimentos no perecederos'),
  ('Caraotas', 'official', 'kg', 'Alimentos no perecederos'),
  ('Atún en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Sardinas en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Guisantes en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Garbanzos en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Carne de res en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Goulash en lata', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Leche en polvo', 'official', 'kg', 'Alimentos no perecederos'),
  ('Avena', 'official', 'kg', 'Alimentos no perecederos'),
  ('Aceite', 'official', 'litro', 'Alimentos no perecederos'),
  ('Sal', 'official', 'kg', 'Alimentos no perecederos'),
  ('Azúcar', 'official', 'kg', 'Alimentos no perecederos'),
  ('Electrolitos en polvo', 'official', 'caja', 'Alimentos no perecederos'),
  ('Barras de proteína', 'official', 'unidad', 'Alimentos no perecederos'),
  ('Leche de larga duración', 'official', 'litro', 'Alimentos no perecederos'),
  ('Frutos secos', 'official', 'kg', 'Alimentos no perecederos'),
  ('Cereales', 'official', 'paquete', 'Alimentos no perecederos'),
  ('Protector solar', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Suero oral', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Sales de rehidratación', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Gasas', 'official', 'paquete', 'Salud y primeros auxilios'),
  ('Vendas', 'official', 'paquete', 'Salud y primeros auxilios'),
  ('Apósitos', 'official', 'paquete', 'Salud y primeros auxilios'),
  ('Esparadrapo', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Guantes desechables', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Mascarillas', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Alcohol en gel', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Antisépticos', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Termómetros', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Solución salina', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Kits de primeros auxilios', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Inyectadoras', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Glucómetro', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Tensiómetro', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Yeso', 'official', 'unidad', 'Salud y primeros auxilios'),
  ('Antibióticos', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Pastillas para la tensión', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Pastillas para el dolor', 'official', 'caja', 'Salud y primeros auxilios'),
  ('Fórmula infantil nueva y sellada', 'official', 'unidad', 'Niños y bebés'),
  ('Comida para bebés en envase sellado', 'official', 'unidad', 'Niños y bebés'),
  ('Toallitas', 'official', 'paquete', 'Niños y bebés'),
  ('Jabón infantil', 'official', 'unidad', 'Niños y bebés'),
  ('Cepillos infantiles', 'official', 'unidad', 'Niños y bebés'),
  ('Ropa nueva para niños', 'official', 'unidad', 'Niños y bebés'),
  ('Sábanas nuevas', 'official', 'unidad', 'Niños y bebés'),
  ('Jabón corporal', 'official', 'unidad', 'Adultos mayores'),
  ('Colchonetas', 'official', 'unidad', 'Adultos mayores'),
  ('Alimentos suaves', 'official', 'unidad', 'Adultos mayores'),
  ('Guantes de cuidado', 'official', 'caja', 'Adultos mayores'),
  ('Escobas', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Palas', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Cepillos duros', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Baldes', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Trapos', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Desinfectantes', 'official', 'litro', 'Limpieza y recuperación'),
  ('Bolsas de basura resistentes', 'official', 'paquete', 'Limpieza y recuperación'),
  ('Guantes gruesos', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Mascarillas contra polvo', 'official', 'caja', 'Limpieza y recuperación'),
  ('Gafas', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Costales', 'official', 'unidad', 'Limpieza y recuperación'),
  ('Gorras', 'official', 'unidad', 'Limpieza y recuperación');
commit;
